<?php
$activePage = 'citas-administracion';
$pageTitle = 'Manage Appointments | JingleWorks';
$pageHeadExtras = '<link rel="stylesheet" href="css/citas-administracion.css" />';
// Admin appointment view. Selecting a user reloads this page with idUser in query string.
include root_path('includes/header.php');
?>
<main class="citas-administracion-page"><div class="container">
  <h1>Manage User Appointments</h1>
  <?php if (!empty($errors)) : ?><div class="form-messages error"><ul><?php foreach ($errors as $error) : ?><li><?= e($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
  <?php if (!empty($success)) : ?><div class="form-messages success"><ul><li><?= e($success) ?></li></ul></div><?php endif ?>
  <section class="user-selection"><h2>Select a User</h2><form method="GET" action="index.php" class="user-select-form"><input type="hidden" name="page" value="admin-appointments"><div class="form-group"><label for="idUser">User:</label><select id="idUser" name="idUser" required onchange="this.form.submit()"><option value="">-- Choose a User --</option><?php foreach ($usersData as $user) : ?><option value="<?= e($user['idUser']) ?>" <?= $selectedIdUser == $user['idUser'] ? 'selected' : '' ?>><?= e($user['nombre'] . ' ' . $user['apellidos'] . ' (' . $user['email'] . ')') ?></option><?php endforeach ?></select></div></form></section>
  <?php if (!empty($selectedIdUser) && $selectedUserDetails) : ?>
    <section class="user-details"><h2>User Information</h2><div class="details-grid"><div class="detail-item"><strong>Name:</strong> <?= e($selectedUserDetails['nombre'] . ' ' . $selectedUserDetails['apellidos']) ?></div><div class="detail-item"><strong>Email:</strong> <?= e($selectedUserDetails['email']) ?></div><div class="detail-item"><strong>Phone:</strong> <?= e($selectedUserDetails['telefono']) ?></div></div></section>
    <section class="create-appointment"><h2>Create New Appointment</h2><form method="POST" action="index.php?page=admin-appointment-create" class="appointment-form"><input type="hidden" name="idUser" value="<?= e($selectedIdUser) ?>"><div class="form-group"><label for="fecha_cita">Appointment Date:</label><input type="date" id="fecha_cita" name="fecha_cita" required min="<?= date('Y-m-d') ?>"></div><div class="form-group"><label for="motivo_cita">Reason for Appointment:</label><textarea id="motivo_cita" name="motivo_cita" rows="4" required></textarea></div><button type="submit" class="btn btn-primary">Create Appointment</button></form></section>
    <section class="user-appointments"><h2>Appointments for This User</h2><?php if (empty($citasData)) : ?><p class="no-appointments">This user has no scheduled appointments yet.</p><?php else : ?><div class="appointments-list"><?php foreach ($citasData as $cita) : ?><?php $appointmentDate = new DateTime($cita['fecha_cita']); $isFuture = $appointmentDate >= new DateTime('today'); ?><div class="appointment-card <?= $isFuture ? 'future' : 'past' ?>"><div class="appointment-header"><h3><?= e($appointmentDate->format('F d, Y')) ?></h3><span class="appointment-status <?= $isFuture ? 'status-upcoming' : 'status-completed' ?>"><?= $isFuture ? 'Upcoming' : 'Completed' ?></span></div><div class="appointment-content"><p><strong>Reason:</strong></p><p><?= e($cita['motivo_cita']) ?></p></div><div class="appointment-actions"><button type="button" class="btn btn-edit" onclick="openEditModal(<?= e(json_encode($cita)) ?>)">Edit</button><form method="POST" action="index.php?page=admin-appointment-delete" class="delete-form" onsubmit="return confirm('Are you sure you want to delete this appointment?');"><input type="hidden" name="idUser" value="<?= e($selectedIdUser) ?>"><input type="hidden" name="idCita" value="<?= e($cita['idCita']) ?>"><button type="submit" class="btn btn-delete">Delete</button></form></div></div><?php endforeach ?></div><?php endif ?></section>
  <?php endif ?>
</div></main>
<div id="editModal" class="modal"><div class="modal-content"><span class="close" onclick="closeEditModal()">&times;</span><h2>Edit Appointment</h2><form method="POST" action="index.php?page=admin-appointment-update" class="appointment-form"><input type="hidden" name="idUser" value="<?= e($selectedIdUser) ?>"><input type="hidden" id="editIdCita" name="idCita"><div class="form-group"><label for="editFechaCita">Appointment Date:</label><input type="date" id="editFechaCita" name="fecha_cita" required min="<?= date('Y-m-d') ?>"></div><div class="form-group"><label for="editMotivoCita">Reason for Appointment:</label><textarea id="editMotivoCita" name="motivo_cita" rows="4" required></textarea></div><div class="modal-actions"><button type="submit" class="btn btn-primary">Save Changes</button><button type="button" class="btn btn-secondary" onclick="closeEditModal()">Cancel</button></div></form></div></div>
<script>
// Seeds the appointment edit modal for the selected user's appointment.
function openEditModal(cita){document.getElementById('editIdCita').value=cita.idCita;document.getElementById('editFechaCita').value=cita.fecha_cita;document.getElementById('editMotivoCita').value=cita.motivo_cita;document.getElementById('editModal').style.display='block';}
function closeEditModal(){document.getElementById('editModal').style.display='none';}
</script>
<?php $footerExtra = ''; include root_path('includes/footer.php'); ?>
